#!/usr/bin/env python3
import os, json
from pathlib import Path

KENV_STATEFUL_EDIT = json.loads(os.environ.get('KENV_STATEFUL_EDIT', 'false').lower())
assert isinstance(KENV_STATEFUL_EDIT, bool)

KENV_KGYM_ENDPOINT = os.environ['KENV_KGYM_ENDPOINT']
KENV_SYZBOT_BUG_ID = os.environ['KENV_SYZBOT_BUG_ID']

import asyncio
from KBDr.kclient import kGymAgentClient

if __name__ == '__main__':
    client = kGymAgentClient(
        KENV_KGYM_ENDPOINT,
        '/linux',
        KENV_SYZBOT_BUG_ID,
        '/KBDr/kBench.json',
        '/KBDr/kEval.json',
        '/KBDr/storageCfg.json'
    )

    async def run():
        await client.connect()
        try:
            # write crash report;
            Path('/root/report.txt').write_text(client.bug.rawCrashReport)
            repro = 'No reproducer available.'
            if client.bug.crashes[0].cReproducer:
                repro = client.bug.crashes[0].cReproducer
            if client.bug.crashes[0].syzReproducer:
                repro = client.bug.crashes[0].syzReproducer
            repro = '\n'.join(repro.splitlines()[2:])
            Path('/root/reproducer.txt').write_text(repro)
        finally:
            await client.close()

    asyncio.run(run())
