#!/usr/bin/env python3
import os, json

KENV_STATEFUL_EDIT = json.loads(os.environ.get('KENV_STATEFUL_EDIT', 'false').lower())
assert isinstance(KENV_STATEFUL_EDIT, bool)
if not KENV_STATEFUL_EDIT:
    print('Stateful edit is not allowed in the current environment.')
    quit()

KENV_KGYM_ENDPOINT = os.environ['KENV_KGYM_ENDPOINT']
KENV_SYZBOT_BUG_ID = os.environ['KENV_SYZBOT_BUG_ID']

import asyncio
from KBDr.kclient import kGymAgentClient

if __name__ == '__main__':
    if 'GOOGLE_APPLICATION_CREDENTIALS' in os.environ:
        del os.environ['GOOGLE_APPLICATION_CREDENTIALS']
    client = kGymAgentClient(
        KENV_KGYM_ENDPOINT,
        '/linux',
        KENV_SYZBOT_BUG_ID,
        '/KBDr/kBench.json',
        '/KBDr/kEval.json',
        '/KBDr/storageCfg.json'
    )

    async def run():
        await client.connect()
        try:
            await client.run(
                await client.get_patch(),
                ninstance=5
            )
        finally:
            await client.close()

    asyncio.run(run())
    print(client.tool_observation)
